name: Platform JS Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run_tests:
    name: Javascript Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8' ]

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Required Packages
      run: |
        sudo apt-get update && sudo apt-get install libxmlsec1-dev
    - name: Install pip
      run: pip install -r requirements/edx/pip-tools.txt

    - name: Install Python Dependencies
      run: |
        node --version
        pip install setuptools wheel
        pip install -r requirements/edx/development.txt

    - uses: actions/setup-node@v2
    - name: Run Tests
      with:
        node-version: '12'
      env:
        FIREFOX_BIN: /usr/bin/firefox
        TEST_SUITE: js-unit
        SCRIPT_TO_RUN: ./scripts/generic-ci-tests.sh
      run: ./scripts/all-tests.sh
